"apiVersion": "batch/v1beta1"
"kind": "CronJob"
"metadata":
  "name": "cronjob-cleanup"
"spec":
  "jobTemplate":
    "spec":
      "backoffLimit": 0
      "template":
        "spec":
          "containers":
          - "args":
            - |
              cat > tests.txt <<EOF
              flax-latest-imagenet-conv-v3-32-1vm
              flax-latest-imagenet-func-v3-32-1vm
              jax-pod-head-libtpu-nightly-func-v2-32-1vm
              jax-pod-latest-libtpu-alpha-func-v2-32-1vm
              jax-pod-latest-libtpu-nightly-func-v2-32-1vm
              pt-nightly-fs-transformer-func-v3-32
              pt-nightly-resnet50-mp-conv-v3-32
              pt-nightly-resnet50-pod-func-v3-32
              pt-nightly-roberta-pre-func-v3-32
              pt-r1.8.1-fs-transformer-func-v3-32
              pt-r1.8.1-mnist-conv-v3-32-1vm
              pt-r1.8.1-resnet50-mp-conv-v3-32
              pt-r1.8.1-resnet50-mp-func-v3-32-1vm
              pt-r1.8.1-resnet50-pod-func-v3-32
              pt-r1.8.1-roberta-pre-func-v3-32
              pt-r1.9-mnist-conv-v3-32-1vm
              pt-r1.9-resnet50-mp-func-v3-32-1vm
              pt-r1.9-resnet50-pod-func-v3-32
              pt-r1.9-roberta-pre-func-v3-32
              tf-nightly-bert-mnli-conv-v2-32
              tf-nightly-bert-mnli-conv-v3-32
              tf-nightly-bert-mnli-func-v2-32-1vm
              tf-nightly-bert-mnli-func-v3-32
              tf-nightly-bert-mnli-func-v3-32-1vm
              tf-nightly-classifier-efficientnet-conv-v2-32
              tf-nightly-classifier-efficientnet-conv-v3-32
              tf-nightly-classifier-efficientnet-func-v2-32
              tf-nightly-classifier-efficientnet-func-v2-32-1vm
              tf-nightly-classifier-efficientnet-func-v3-32
              tf-nightly-classifier-resnet-conv-v2-32
              tf-nightly-classifier-resnet-conv-v3-32
              tf-nightly-classifier-resnet-func-v2-32
              tf-nightly-classifier-resnet-func-v2-32-1vm
              tf-nightly-classifier-resnet-func-v3-32
              tf-nightly-classifier-resnet-func-v3-32-1vm
              tf-nightly-classifier-resnetrs-conv-v2-32
              tf-nightly-classifier-resnetrs-conv-v3-32
              tf-nightly-classifier-resnetrs-func-v2-32
              tf-nightly-classifier-resnetrs-func-v3-32
              tf-nightly-efficientnet-perfzero-v3-32
              tf-nightly-keras-api-connection-v2-32
              tf-nightly-keras-api-connection-v3-32
              tf-nightly-keras-api-ctl-v2-32
              tf-nightly-keras-api-ctl-v3-32
              tf-nightly-keras-api-custom-layers-v2-32
              tf-nightly-keras-api-feature-column-v3-32
              tf-nightly-keras-api-preprocess-layers-v3-32
              tf-nightly-keras-api-rnn-v2-32
              tf-nightly-keras-api-save-and-load-v2-32
              tf-nightly-keras-api-save-load-localhost-v2-32
              tf-nightly-keras-api-train-and-evaluate-v2-32
              tf-nightly-keras-api-train-and-evaluate-v3-32
              tf-nightly-keras-api-train-eval-dataset-v3-32
              tf-nightly-keras-api-transfer-learning-v3-32
              tf-nightly-maskrcnn-conv-v2-32
              tf-nightly-maskrcnn-conv-v3-32
              tf-nightly-maskrcnn-func-v2-32
              tf-nightly-maskrcnn-func-v2-32-1vm
              tf-nightly-maskrcnn-func-v3-32
              tf-nightly-maskrcnn-perfzero-v3-32
              tf-nightly-mnist-conv-v2-32-1vm
              tf-nightly-ncf-conv-v2-32
              tf-nightly-ncf-func-v2-32-1vm
              tf-nightly-ncf-func-v3-32
              tf-nightly-ranking-dcn-conv-v3-32
              tf-nightly-ranking-dcn-func-v2-32
              tf-nightly-ranking-dlrm-conv-v3-32
              tf-nightly-ranking-dlrm-func-v3-32
              tf-nightly-resnet-ctl-conv-v2-32
              tf-nightly-resnet-ctl-conv-v3-32
              tf-nightly-resnet-ctl-func-v2-32-1vm
              tf-nightly-resnet-ctl-func-v3-32
              tf-nightly-resnet50-cfit-perfzero-v3-32
              tf-nightly-resnet50-ctl-perfzero-v3-32
              tf-nightly-retinanet-conv-v2-32
              tf-nightly-retinanet-conv-v3-32
              tf-nightly-retinanet-func-v2-32
              tf-nightly-retinanet-func-v2-32-1vm
              tf-nightly-retinanet-func-v3-32
              tf-nightly-retinanet-perfzero-v3-32
              tf-nightly-shapemask-conv-v3-32
              tf-nightly-shapemask-func-v2-32
              tf-nightly-shapemask-func-v2-32-1vm
              tf-nightly-shapemask-func-v3-32
              tf-nightly-shapemask-perfzero-v3-32
              tf-nightly-transformer-perfzero-v3-32
              tf-nightly-transformer-translate-conv-v2-32
              tf-nightly-transformer-translate-conv-v3-32
              tf-nightly-transformer-translate-func-v2-32
              tf-nightly-transformer-translate-func-v2-32-1vm
              tf-nightly-transformer-translate-func-v3-32
              tf-nightly-xlnet-imdb-conv-v2-32
              tf-nightly-xlnet-imdb-conv-v3-32
              tf-r1.15.5-bert-conv-v2-32
              tf-r1.15.5-bert-conv-v3-32
              tf-r1.15.5-efficientnet-conv-v2-32
              tf-r1.15.5-efficientnet-conv-v3-32
              tf-r1.15.5-mask-rcnn-conv-v2-32
              tf-r1.15.5-mask-rcnn-conv-v3-32
              tf-r1.15.5-mnasnet-conv-v2-32
              tf-r1.15.5-mnasnet-conv-v3-32
              tf-r1.15.5-resnet-conv-v2-32
              tf-r1.15.5-resnet-conv-v3-32
              tf-r1.15.5-retinanet-conv-v2-32
              tf-r1.15.5-retinanet-conv-v3-32
              tf-r1.15.5-shapemask-conv-v2-32
              tf-r1.15.5-shapemask-conv-v3-32
              tf-r1.15.5-transformer-conv-v2-32
              tf-r1.15.5-transformer-conv-v3-32
              tf-r1.15.5-unet-conv-v2-32
              tf-r1.15.5-unet-conv-v3-32
              tf-r2.2.3-resnet-ctl-conv-v2-32
              tf-r2.2.3-resnet-ctl-conv-v3-32
              tf-r2.3.2-classifier-resnet-conv-v2-32
              tf-r2.3.2-classifier-resnet-conv-v3-32
              tf-r2.4.2-keras-api-connection-v2-32
              tf-r2.4.2-keras-api-connection-v3-32
              tf-r2.4.2-keras-api-ctl-v2-32
              tf-r2.4.2-keras-api-ctl-v3-32
              tf-r2.4.2-keras-api-custom-layers-v2-32
              tf-r2.4.2-keras-api-feature-column-v3-32
              tf-r2.4.2-keras-api-preprocess-layers-v3-32
              tf-r2.4.2-keras-api-rnn-v2-32
              tf-r2.4.2-keras-api-save-and-load-v2-32
              tf-r2.4.2-keras-api-save-load-localhost-v2-32
              tf-r2.4.2-keras-api-train-and-evaluate-v2-32
              tf-r2.4.2-keras-api-train-and-evaluate-v3-32
              tf-r2.4.2-keras-api-train-eval-dataset-v3-32
              tf-r2.4.2-keras-api-transfer-learning-v3-32
              tf-r2.5.0-bert-mnli-conv-v3-32
              tf-r2.5.0-bert-mnli-func-v2-32
              tf-r2.5.0-bert-mnli-func-v3-32
              tf-r2.5.0-classifier-efficientnet-conv-v3-32
              tf-r2.5.0-classifier-efficientnet-func-v2-32
              tf-r2.5.0-classifier-efficientnet-func-v3-32
              tf-r2.5.0-classifier-resnet-conv-v3-32
              tf-r2.5.0-classifier-resnet-func-v2-32
              tf-r2.5.0-classifier-resnet-func-v3-32
              tf-r2.5.0-keras-api-connection-v2-32
              tf-r2.5.0-keras-api-connection-v3-32
              tf-r2.5.0-keras-api-ctl-v2-32
              tf-r2.5.0-keras-api-ctl-v3-32
              tf-r2.5.0-keras-api-custom-layers-v2-32
              tf-r2.5.0-keras-api-feature-column-v3-32
              tf-r2.5.0-keras-api-preprocess-layers-v3-32
              tf-r2.5.0-keras-api-rnn-v2-32
              tf-r2.5.0-keras-api-save-and-load-v2-32
              tf-r2.5.0-keras-api-save-load-localhost-v2-32
              tf-r2.5.0-keras-api-train-and-evaluate-v2-32
              tf-r2.5.0-keras-api-train-and-evaluate-v3-32
              tf-r2.5.0-keras-api-train-eval-dataset-v3-32
              tf-r2.5.0-keras-api-transfer-learning-v3-32
              tf-r2.5.0-maskrcnn-conv-v3-32
              tf-r2.5.0-maskrcnn-func-v2-32
              tf-r2.5.0-maskrcnn-func-v3-32
              tf-r2.5.0-ncf-func-v3-32
              tf-r2.5.0-ranking-dcn-conv-v3-32
              tf-r2.5.0-ranking-dcn-func-v2-32
              tf-r2.5.0-ranking-dlrm-conv-v3-32
              tf-r2.5.0-ranking-dlrm-func-v3-32
              tf-r2.5.0-resnet-ctl-conv-v3-32
              tf-r2.5.0-resnet-ctl-func-v2-32
              tf-r2.5.0-resnet-ctl-func-v3-32
              tf-r2.5.0-retinanet-conv-v3-32
              tf-r2.5.0-retinanet-func-v2-32
              tf-r2.5.0-retinanet-func-v3-32
              tf-r2.5.0-shapemask-conv-v3-32
              tf-r2.5.0-shapemask-func-v2-32
              tf-r2.5.0-shapemask-func-v3-32
              tf-r2.5.0-transformer-translate-conv-v3-32
              tf-r2.5.0-transformer-translate-func-v2-32
              tf-r2.5.0-transformer-translate-func-v3-32
              tf-r2.5.0-xlnet-imdb-conv-v3-32
              tf-r2.6.0-bert-mnli-conv-v3-32
              tf-r2.6.0-bert-mnli-func-v3-32
              tf-r2.6.0-classifier-efficientnet-conv-v3-32
              tf-r2.6.0-classifier-efficientnet-func-v2-32
              tf-r2.6.0-classifier-efficientnet-func-v3-32
              tf-r2.6.0-classifier-resnet-conv-v3-32
              tf-r2.6.0-classifier-resnet-func-v2-32
              tf-r2.6.0-classifier-resnet-func-v3-32
              tf-r2.6.0-classifier-resnetrs-conv-v3-32
              tf-r2.6.0-classifier-resnetrs-func-v2-32
              tf-r2.6.0-classifier-resnetrs-func-v3-32
              tf-r2.6.0-keras-api-connection-v2-32
              tf-r2.6.0-keras-api-connection-v3-32
              tf-r2.6.0-keras-api-ctl-v2-32
              tf-r2.6.0-keras-api-ctl-v3-32
              tf-r2.6.0-keras-api-custom-layers-v2-32
              tf-r2.6.0-keras-api-feature-column-v3-32
              tf-r2.6.0-keras-api-preprocess-layers-v3-32
              tf-r2.6.0-keras-api-rnn-v2-32
              tf-r2.6.0-keras-api-save-and-load-v2-32
              tf-r2.6.0-keras-api-save-load-localhost-v2-32
              tf-r2.6.0-keras-api-train-and-evaluate-v2-32
              tf-r2.6.0-keras-api-train-and-evaluate-v3-32
              tf-r2.6.0-keras-api-train-eval-dataset-v3-32
              tf-r2.6.0-keras-api-transfer-learning-v3-32
              tf-r2.6.0-maskrcnn-conv-v3-32
              tf-r2.6.0-maskrcnn-func-v2-32
              tf-r2.6.0-maskrcnn-func-v3-32
              tf-r2.6.0-ncf-func-v3-32
              tf-r2.6.0-ranking-dcn-conv-v3-32
              tf-r2.6.0-ranking-dcn-func-v2-32
              tf-r2.6.0-ranking-dlrm-conv-v3-32
              tf-r2.6.0-ranking-dlrm-func-v3-32
              tf-r2.6.0-resnet-ctl-conv-v3-32
              tf-r2.6.0-resnet-ctl-func-v3-32
              tf-r2.6.0-retinanet-conv-v3-32
              tf-r2.6.0-retinanet-func-v2-32
              tf-r2.6.0-retinanet-func-v3-32
              tf-r2.6.0-shapemask-conv-v3-32
              tf-r2.6.0-shapemask-func-v2-32
              tf-r2.6.0-shapemask-func-v3-32
              tf-r2.6.0-transformer-translate-conv-v3-32
              tf-r2.6.0-transformer-translate-func-v2-32
              tf-r2.6.0-transformer-translate-func-v3-32
              tf-r2.6.0-xlnet-imdb-conv-v3-32
              EOF
              
              delete_list=$(kubectl get cronjob --namespace=automated -l benchmarkId -o name | grep -v -f tests.txt)
              if [[ "$delete_list" ]]; then
                kubectl delete $delete_list;
              fi
            "command":
            - "bash"
            - "-cx"
            "image": "google/cloud-sdk"
            "name": "clean"
          "restartPolicy": "Never"
          "serviceAccount": "cronjob-cleaner"
  "schedule": "0 */4 * * *"